# Generated by Django 3.2.25 on 2025-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Категория расходов')),
                ('category_place_on_the_list', models.IntegerField(verbose_name='Номер в списке')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_name', models.CharField(max_length=255, verbose_name='Месяц')),
                ('Month_number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash_expenses', models.IntegerField(verbose_name='Расходы за наличные')),
                ('Month_name', models.ForeignKey(on_delete=models.SET('Не корректное название месяца'), to='core.months', verbose_name='Категории')),
                ('category_name', models.ForeignKey(on_delete=models.SET('Категория не найдена'), to='core.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
