# Generated by Django 3.2.25 on 2025-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='months',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцев'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='Month_name',
            field=models.ForeignKey(on_delete=models.SET('Не корректное название месяца'), to='core.months', verbose_name='Месяц'),
        ),
        migrations.CreateModel(
            name='HugeExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Крупные траты за год')),
                ('Cash_expenses', models.IntegerField(verbose_name='Расходы за наличные')),
                ('Month_name', models.ForeignKey(on_delete=models.SET('Не корректное название месяца'), to='core.months', verbose_name='Месяц')),
                ('category_name', models.ForeignKey(on_delete=models.SET('Категория не найдена'), to='core.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Крупные траты за год',
                'verbose_name_plural': 'Крупные траты за год',
            },
        ),
    ]
