# Generated by Django 3.2.25 on 2025-10-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250915_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Категория расходов')),
                ('category_place_on_the_list', models.IntegerField(verbose_name='Номер в списке')),
                ('limit', models.IntegerField(null=True, verbose_name='Лимит расходов по категории')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расходов',
            },
        ),
        migrations.CreateModel(
            name='CategoryIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Категория расходов')),
                ('category_place_on_the_list', models.IntegerField(verbose_name='Номер в списке')),
            ],
            options={
                'verbose_name': 'Категория дохода',
                'verbose_name_plural': 'Категории доходов',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash_expenses', models.IntegerField(verbose_name='Расходы за наличные')),
                ('date_created', models.DateField(verbose_name='Дата расхода')),
                ('waste_name', models.TextField(verbose_name='Описание расхода')),
                ('category_name', models.ForeignKey(on_delete=models.SET('Категория не найдена'), to='core.categoryexpenses', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Сумма дохода')),
                ('date_created', models.DateField(verbose_name='Дата дохода')),
                ('income_name', models.TextField(verbose_name='Описание дохода')),
                ('category_id', models.ForeignKey(on_delete=models.SET('Доход не привязан к категории'), to='core.categoryincome', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_acсount', models.IntegerField(verbose_name='Деньги на банковском счете')),
                ('cash', models.IntegerField(verbose_name='Наличные деньги ')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.RenameField(
            model_name='hugeexpenses',
            old_name='Cash_expenses',
            new_name='cash_expenses',
        ),
        migrations.RenameField(
            model_name='hugeexpenses',
            old_name='Month_name',
            new_name='month_name',
        ),
        migrations.RenameField(
            model_name='months',
            old_name='Month_name',
            new_name='month_name',
        ),
        migrations.RenameField(
            model_name='months',
            old_name='Month_number',
            new_name='month_number',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='month_name',
            field=models.ForeignKey(on_delete=models.SET('Не корректное название месяца'), to='core.months', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='hugeexpenses',
            name='category_name',
            field=models.ForeignKey(on_delete=models.SET('Категория не найдена'), to='core.categoryexpenses', verbose_name='Категории'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
