# Generated by Django 3.2.25 on 2025-11-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251007_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Cash_expenses',
            new_name='cash_expenses',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoryexpenses', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.months', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='hugeexpenses',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoryexpenses', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='hugeexpenses',
            name='month_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.months', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoryincome', verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HugeExpensesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма при которой расход выводится в разделе "Крупные траты"')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoryexpenses', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Настройка для крупной траты',
                'verbose_name_plural': 'Настройки для крупных трат',
            },
        ),
    ]
