# Generated by Django 3.2.25 on 2025-11-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251116_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category_id',
        ),
        migrations.AddField(
            model_name='income',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoryincome', verbose_name='Доход'),
        ),
        migrations.AddField(
            model_name='income',
            name='month_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.months', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расхода'),
        ),
    ]
