# Generated by Django 4.2 on 2025-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_user_id_profile_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_acсount',
            field=models.IntegerField(default=0, verbose_name='Деньги на банковском счете'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=0, verbose_name='Наличные деньги '),
        ),
    ]
