# Generated by Django 4.2 on 2025-12-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_bank_acсount_alter_profile_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.profile'),
        ),
        migrations.AddField(
            model_name='income',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.profile'),
        ),
    ]
